### ISSUE TITLE
Please submit to F-Droid project?

### ISSUE THREAD

**Issue by Pentaphon** [fm-sys/snapdrop-android#27] opened 2020-12-18 16:58 UTC
Would be nice to submit this to https://f-droid.org/ so we can keep it up to date. 

More info here: https://f-droid.org/en/docs/FAQ_-_App_Developers/

**Comment by fm-sys** [comment] 2020-12-18 23:58
Would be very cool for sure! However I have no idea, if there are some special conditions which must be fulfilled or something like that. I've read the FAQ but the procedure of adding a new app seems a bit cryptic to me. 

I also saw other open source apps which are using their own f-droid repo which can be added as package sources in the f-droid app. Would that be a way to go, or could you (or someone else) help with bringing this app to f-droid?

**Comment by Pentaphon** [comment] 2020-12-22 17:28
Here's the template you need to follow if you choose to submit there.

**Comment by fm-sys** [comment] 2021-01-06 18:28
Note to myself: https://dev.to/sanandmv7/how-to-publish-your-apps-on-f-droid-2epn

**Comment by fm-sys** [comment] 2021-01-09 12:33
I totally understand why you would like to see this app at F-Droid. However, the downside of F-Droid is that they build the APK from source their selves with a different signature, so it would not be compatible with the releases on GitHub and in the future with Google Play (#30). 

Therefore, you can use the [binary repo IzzyOnDroid](https://apt.izzysoft.de/fdroid/index/apk/com.fmsys.snapdrop) as a workaround, which you can add as extra package source to the F-Droid client.

**Comment by Pentaphon** [comment] 2021-01-09 12:37
> Therefore, you can use the [binary repo IzzyOnDroid](https://apt.izzysoft.de/fdroid/index/apk/com.fmsys.snapdrop) as a workaround, which you can add as extra package source to the F-Droid client.

That's good enough. Just wanted at least 1 way to update this without having to check over and over. Closing. Thanks.

**Comment by jnnkB** [comment] 2021-03-21 13:10
I still would like to see this app in the fdroid repo since they build the app and use reproducible build this is still more trustworthy than the IzzyOnDroid repo or GitHub Releases. Is this something you would consider @fm-sys?

**Comment by fm-sys** [comment] 2021-03-21 13:21
If someone else wants to help me/do it for me, why not. Would be very welcome! 
But I currently do not plan to do it myself, because I simply don't have the knowledge. BTW, meanwhile "Snapdrop for Android" is also available at [Google Play](https://play.google.com/store/apps/details?id=com.fmsys.snapdrop) (nowadays they scan the apps before publishing) or you need to build the apk by yourself, if you don't trust me ;-)

**Comment by fm-sys** [comment] 2021-05-27 05:54
@IzzySoft

I have read your offer to help submitting the "DeepL" app to f-droid. (https://github.com/sakusaku3939/DeepLAndroid/issues/7) 

Would you be willing to help me for "Snapdrop for Android" as well?

**Comment by IzzySoft** [comment] 2021-05-29 22:40
@fm-sys apologies for the late reply (I did not yet manage the trick to be in multiple places simultaneously), but [here you go](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/9080). I might need to address you during review. Hints for on-device-test are welcome, for example: next to the Android test device, I'd have a Linux machine available. Or a second Android device – which would probably be the easiest way (installing the app on two Android devices).

**Comment by fm-sys** [comment] 2021-05-30 08:08
@IzzySoft cool, thank you very much! 
Please tell me if there's anything I need to do...

> Hints for on-device-test are welcome, for example: next to the Android test device, I'd have a Linux machine available. Or a second Android device 

Yes, testing can be done easily. Just open the app on an Android device and open https://snapdrop.net or the app as well on the other device. Or provide me a link to the F-Droid APK, which I can test myself.

**Comment by IzzySoft** [comment] 2021-05-30 10:45
Just for clarification: Having the app on two devices does not need any Internet connection, right? Description explicitly states it's device-to-device, so nothing gets routed via snapdrop.net (or any other Internet service)?

**Comment by fm-sys** [comment] 2021-05-30 12:07
Internet connection is still required so that the devices are able to find each other (stun-server). This is done via connecting to the Snapdrop.net website. 

But the files itself are sent directly between devices via webRTC, not via an external server.

BTW, the snapdrop.net website is open source as well: https://github.com/RobinLinus/snapdrop

**Comment by IzzySoft** [comment] 2021-05-30 15:29
> stun-server

Oh. Maybe you can point that out in the app description? I thought it would also provide detection via WiFi direct, without a middle-man needed. Knowing this fact it becomes clear why the phrasing says "Dateien" and not "Daten" – but that fact is easily missed. And we want to avoid such kind of misunderstanding :wink:

> the snapdrop.net website is open source as well

Thanks for pointing out! So we won't need NonFreeNet for this :smiley:

**Comment by fm-sys** [comment] 2021-05-30 15:55
What about this one:
"This app connects to https://snapdrop.net/ to provide cross-platform file sharing functionality. However, none of your files is ever sent to any server but are transferred peer-to-peer within your local network."

**Comment by IzzySoft** [comment] 2021-05-30 15:59
Maybe explicitly state "discovery" instead of "sharing" – unless files indeed go via that stun server, and not only the connection, which would contradict the "none of your files is ever sent to any server but are transferred peer-to-peer".

Apart from that, please check out [my review](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/9080#note_588457065) – a bunch of other questions came up during review/test (like connections to multiple other servers, or the app not transferring either files or messages).

**Comment by danielphan2003** [comment] 2021-06-16 11:26
F-Droid build is currently broken for me :(. My computer can't detect my phone and neither could it. The Play Store one is fine though, so I guess I'd use that for now.

**Comment by fm-sys** [comment] 2021-11-23 17:19
"Snapdrop for Android" is available since quite some time on F-Droid meanwhile, I think we can close here... Many thanks again to @IzzySoft for your help!

Check out: https://f-droid.org/en/packages/com.fmsys.snapdrop/

**Closed by fm-sys** 2021-11-23 17:19 UTC
Labels: feature request
