### ISSUE TITLE
The App WebView kernel caused the transfer file to be unresponsive

### ISSUE THREAD

**Issue by coffee1boy** [fm-sys/snapdrop-android#137] opened 2021-11-23 06:41 UTC
It can work normally on Huawei mobile phones, but not on Xiaomi mobile phones. However, snapdrop can be used to use Huawei browser on Xiaomi mobile phones. Doubt is a problem with WebRTC.Can I replace the kernel?

**Comment by fm-sys** [comment] 2021-11-23 14:19
Does your device have the Google Play services installed, or is it a Google free device?

On normal Android devices, [this app](https://play.google.com/store/apps/details?id=com.google.android.webview) is providing the system webview implementation and is installed on all devices by default... Is it installed on your device as well?

**Comment by fm-sys** [comment] 2021-12-31 09:41
Hi @coffee1boy,

I will close the issue for now, due to the lack of necessary information. Feel free to comment if you have more details... I will reopen the issue as soon as I can reproduce it.

**Closed by fm-sys** 2021-12-31 09:41 UTC
Labels: bug, Waiting for more information
