### ISSUE TITLE
Support pairdrop.net

### ISSUE THREAD

**Issue by Warden20** [fm-sys/snapdrop-android#246] opened 2023-02-01 23:23 UTC
### Describe the feature

Sometime the official instance is down. I tried one of the inofficial intances, this one https://pairdrop.net/. But the app doesnt work with it. Can you make the app compatible with this instance?

### Describe alternatives you've considered

https://github.com/schlagmichdoch/pairdrop 
This is the repository

**Comment by fm-sys** [comment] 2023-02-05 01:31
In the most recent release, you should be able to set https://pairdrop.net/ as base URL. However, there seem to be some incompatibilities which however should IMHO be fixed on their side...

**Comment by schlagmichdoch** [comment] 2023-02-12 04:14
Thanks @fm-sys !
I will take a look into this as soon as I get my Android phone back for testing. Any idea as to what is causing the incompatibility?

**Comment by fm-sys** [comment] 2023-02-12 12:41
Snapdrop for Android is heavily using JS manipulation to interact with the website. Most likely some JS method name or html structure was changed or something like that. However, I haven't looked deeper into it yet.

**Comment by fm-sys** [comment] 2023-02-12 13:48
@schlagmichdoch do you have the possibility to build Snapdrop for Android yourself inside Android Studio? If not, I could provide you a version with webview debugging enabled...

https://developer.chrome.com/docs/devtools/remote-debugging/webviews/

**Comment by schlagmichdoch** [comment] 2023-02-12 13:59
> Most likely some JS method name or html structure was changed or something like that.

That's most likely true. I changed most of the javascript methods and added some html.



> do you have the possibility to build Snapdrop for Android yourself inside Android Studio?

I'll try that, thanks for asking! I hope there are not too many breaking changes!

**Comment by fm-sys** [comment] 2023-02-12 15:16
Some insights:
This app intercepts the chunk receiving and directly writes the received data into a temporary file instead of serving it via blob. Furthermore, we watch the "download" button and copy the temp file into public storage as soon as the download button was clicked. 
This was done cause streaming a blob was extremely slow on android... (But unfortunately this makes us highly dependent of snapdrops source code)

Is pairdrop based on blob URLs as well?

**Comment by schlagmichdoch** [comment] 2023-02-13 17:54
Thanks!

I got the development environment working using Android Studio but somehow I cannot receive any files via this app no matter wheter I use a PairDrop or Snapdrop instance. The File is received and the ReceiveFileDialog is shown but nothing happens when I click "Download". Is this feature not possible to test via Android Studio right now?

PairDrop still handles everything using blob URLs. There are some changes to html that breaks the translation which is not too bad.
The main breaking change is that multiple files are sent and downloaded at once so there is no event 'file-received' anymore.
As navigator.share is not available to the webview inside Snapdrop for Android, PairDrop creates a ZIP archive of all received files and adds its blob url to the download button. As I understand it, you are not listening to the download button click itself but  you use binding.webview.setDownloadListener. This should be triggered no matter what is downloaded, shouldn't it?

I readded the event 'file-received' in a test branch of PairDrop running live at https://pairdrop-dev.onrender.com/
I would appreciate if you could test whether that is enough to make pairdrop compatibile!

**Comment by fm-sys** [comment] 2023-02-13 23:30
> The File is received and the ReceiveFileDialog is shown but nothing happens when I click "Download". Is this feature not possible to test via Android Studio right now?

Actually this should work... At least with snapdrop.net.

> As I understand it, you are not listening to the download button click itself but you use binding.webview.setDownloadListener. This should be triggered no matter what is downloaded, shouldn't it?

Correct. Unfortunately webviews don't come with native support for downloading blob URLs, so we rely on the data collected via our custom js code.

https://github.com/fm-sys/snapdrop-android/blob/2a434ebb4a20e9850f91db1403537d91bbe4c033/app/src/main/assets/init.js#L103-L122

I've tried to write a not-website-dependent implementation for blob downloads, but didn't get it working.

I followed this example:
https://developer.mozilla.org/en-US/docs/Web/API/ReadableStreamDefaultReader#examples

You'll find my tests here: https://github.com/fm-sys/snapdrop-android/tree/blob_download

![grafik](https://user-images.githubusercontent.com/64581222/218597495-4bfe412c-8d42-4775-bfdf-0ee19306d23d.png)

Do you have any idea why the second part isn't executed?

**Comment by schlagmichdoch** [comment] 2023-02-14 02:33
Hard to know without looking deeper into your code. Injecting script for one language into another is super hard to debug.. Is `mimetype` and `size` set properly?

Don't you think it would be better to develop a client without using javascript injection at all by implementing the complete frontend into the app. Setting the baseurl would then simply change the server address to connect to and change the webrtc configuration. I think this would be much more robust, easier to translate and easier to debug.

I plan to remove the RTCPeer.config from PairDrops network.js and instead get it dynamically from the webserver via the websocket, so getting this configuration would be easy then.

**Comment by fm-sys** [comment] 2023-02-14 11:16
> Don't you think it would be better to develop a client without using javascript injection at all by implementing the complete frontend into the app.

Sure this would be the cleanest solution. However, this would require a common protocol. Is it e.g. easily possible to write a front-end which works for snapdrop.net as well as pairdrop?

Another advantage of writing our own front-end: Snapdrop for Android could implement more technologies in parallel like WiFi direct...

**Comment by schlagmichdoch** [comment] 2023-02-15 13:17
Probably that’s the better approach but rather longterm. First I would love this app to be compatible with PairDrop as it is and help implementing the frontend for this app later, okay? Could you test pairdrop-dev.onrender.com?

**Comment by fm-sys** [comment] 2023-02-20 15:40
Just tested http://pairdrop-dev.onrender.com/, however still doesn't seem to work

**Comment by schlagmichdoch** [comment] 2023-02-20 16:58
Does it not work at all or does it simply not receive any files?

**Comment by fm-sys** [comment] 2023-02-20 17:15
- Sending android -> windows doesn't work (client disappears)
- Sending windows -> android does work. However downloading doesn't work, dialog doesn't even close when hitting "download".

**Comment by schlagmichdoch** [comment] 2023-02-20 19:54
Hm not good. I will look into it again, thanks for testing!

> dialog doesn't even close when hitting "download".

This is currently expected behavior:
https://github.com/schlagmichdoch/PairDrop/issues/40#issuecomment-1437469691

**Comment by ueen** [comment] 2023-03-12 19:01
Didn't see this, the custom front end seems like a lot of work would be great but as this is all just kind of a hobby in spare time I think it's good to reduce complexity and choose practical solutions so if pairdrop could easily be made compatible by renaming functions that would be nice!

I wrote the download logic in the app and it was kind of complicated...the blob download was just to slow for bigger files (like literally minutes).

As for protocol, the js injections should actually already provide a kind of complete set of important points, maybe @schlagmichdoch give some hints what changed in pairdrop
The js injections are here
https://github.com/fm-sys/snapdrop-android/blob/master/app/src/main/assets/init.js should be.pretty straight forward

**Comment by schlagmichdoch** [comment] 2023-03-12 23:56
Thanks for looking into it.

One change of PairDrop is, that the transfer of multiple files must be requested only once and all files are shown/downloaded/shared together after the complete transfer is finished which is an UI improvement IMO.

Anyway, the `_onFilesHeader()` never includes more than one header so I will rename it back to `_onFileHeader()`. This is a remnant of when I zipped all files before sending and unzipped files afterwords which I dropped since to save RAM. I will change it tomorrow and come back to you for testing.

The `fileBlob` object includes a `name` and `size` attribute. The `detail` part comes from it being fired via the `Events.fire()` method. So everything should be alright. :)

**Comment by ueen** [comment] 2023-03-13 08:56
Perfect! Can you provide a test instance to see of it works? :)

**Comment by schlagmichdoch** [comment] 2023-03-13 12:28
With PR #271 downloading mutliple files works🎉  Not sure whether the `iterator.remove();` is needed or whether the iterator is removed from memory automatically after the function finishes.

**Comment by fm-sys** [comment] 2023-03-15 21:34
Let's continue in #269...

**Closed by fm-sys** 2023-03-15 21:34 UTC
Labels: feature request, PairDrop speciffic
