### ISSUE TITLE
Ask for WIFI connection even when I am on WIFI

### ISSUE THREAD

**Issue by askask11** [fm-sys/snapdrop-android#48] opened 2021-02-07 22:23 UTC
**Describe the bug**
The app is asking me to connect to a WIFI even when I am on WIFI.
The warning doesn't disappear no matter how many times I refresh it. The app also refuses to continue.

**To Reproduce**
1. Install the app
2. open the app
3. See the warning
4. Refresh
5. Warning still there

**Expected behavior**
There should not be a warning when I am on WIFI.

**Screenshots**
It is very clear that I AM connected to WIFI. 
The screenshot is shown below:
![Screenshot_20210208_060721_com fmsys snapdrop](https://sourl.cn/TPFpcr)

**Smartphone :**
 - Device: Huawei P30 Pro (VOG-L29)
 - OS: Android 10, EMUI 10.1.0

**Comment by fm-sys** [comment] 2021-02-08 09:00
I have no idea at the moment what the problem could be. For me, it works... Maybe related to multi sim? 🤷 

But I could add a workaround to the settings that allows to disable the WiFi check (would also be in flavor of  #46)

**Comment by askask11** [comment] 2021-02-08 10:55
Yeah. That's a good idea. Perhaps you can also just add little "X" on the WiFi check screen so we can quickly close it.&nbsp;
&nbsp;

社会主义核心价值观:

富强、民主、文明、和谐
 自由、平等、公正、法治
 爱国、敬业、诚信、友善

&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Florian"<notifications@github.com&gt;; 
发送时间: 2021年2月8日(星期一) 下午5:01
收件人: "fm-sys/snapdrop-android"<snapdrop-android@noreply.github.com&gt;; 
抄送: "Johnson Gao"<932646988@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [fm-sys/snapdrop-android] Ask for WIFI connection even when I am on WIFI (#48)





 
I have no idea at the moment what the problem could be. For me, it works... Maybe related to multi sim? 🤷
 
But I could add a workaround to the settings that allows to disable the WiFi check (would also be in flavor of  #46)

**Comment by Sciroccogti** [comment] 2021-04-08 13:16
It might caused by the failure of connecting to github.io, which is blocked in China.

So I guess that this might have been fixed in 2174ad2.

![1617887647336](https://user-images.githubusercontent.com/32357397/114032996-771cb180-98af-11eb-9213-ca1351969f39.jpg)

**Comment by Sciroccogti** [comment] 2021-04-08 13:33
> It might caused by the failure of connecting to github.io, which is blocked in China.
> 
> So I guess that this might have been fixed in [2174ad2](https://github.com/fm-sys/snapdrop-android/commit/2174ad256005d7573208d65f668a30a16b0a8866).

I tried to build the apk with the newest commit, and this issue does seem to be fixed.

**Comment by fm-sys** [comment] 2021-04-08 13:45
Seems like one reason more to release rather soon. I will keep you informed 😉

**Comment by fm-sys** [comment] 2021-04-11 19:20
> 
> Yeah. That's a good idea. Perhaps you can also just add a little "X" on the WiFi check screen so we can quickly close it.

OK, I've implemented a button which will allows you to open snapdrop, even if you are not connected with a WiFi network. It will look like that:

![grafik](https://user-images.githubusercontent.com/64581222/114318060-76805700-9b0b-11eb-953d-b56b5d717167.png)

**Closed** 2021-04-11 19:38 UTC
Labels: bug

**Comment by fm-sys** [comment] 2021-04-11 21:08
New release is created and now is rolling out on Google Play / available at the GitHub release page... @Sciroccogti I would be interested if the issue is solved for you in the new release :)

**Comment by askask11** [comment] 2021-04-12 01:11
The issue seems to be fixed. Thank you'all so much!

**Comment by Sciroccogti** [comment] 2021-04-12 01:54
> New release is created and now is rolling out on Google Play / available at the GitHub release page... @Sciroccogti I would be interested if the issue is solved for you in the new release :)

Yes it's fixed! Thanks!
