### ISSUE TITLE
Zero taps share

### ISSUE THREAD

**Issue by thewh1teagle** [fm-sys/snapdrop-android#239] opened 2022-11-20 12:12 UTC
### Describe the feature

I would like to have the ability to share files between the PC and my Android device with more seamless and convenient way like in airdrop of apple.
The advantage of airdrop over this app, is that you can share the file from / to the PC without opening the app or the desktop app.
You just share it and it instantly sent a notification to the target device.
You can specify if you want to keep it in visible mode or not.
It can be a bit complex to implement but I think that It can take this app level up.

### Describe alternatives you've considered

My plan for that feature implementation:
- It should not depend on notification cloud service such as firebase, only local
- Users should have the ability to choose visible mode
- The Android app need somehow to run background service which get notified in case of new share, we can send it on broadcast

### Additional context

This is how it works on airdrop [YouTube Video](https://www.youtube.com/watch?v=Aymhf_SwScw)

**Comment by fm-sys** [comment] 2023-05-27 18:37
Running a background tasks would only be possible as foreground service (persistent notification in the notification center), everything else gets killed by the OS.

This would cause quite some battery consumption, really worth it?

All in all this seems like a very large task and I won't be able to do this as development is all done in my spare time. If anyone in the community wants to tackle it, feel free! Would be really appreciated!

**Comment by fm-sys** [comment] 2023-05-27 18:51
BTW: rel. to #185

**Comment by fm-sys** [comment] 2024-06-16 19:48
Let's close as duplicate of #185. Thanks again for the feature request!

**Closed by fm-sys** 2024-06-16 19:48 UTC
Labels: feature request
