### ISSUE TITLE
The app crashes when I put many small files into it. And always at the same number, 48

### ISSUE THREAD

**Issue by Thewisem** [fm-sys/snapdrop-android#82] opened 2021-05-01 13:28 UTC
**Describe the bug**
Exactly as the title says

**To Reproduce**
1. Go to Snapdrop
2. Click on the device
3. Click many files to send. And wait

**Expected behavior**
Stay until it is finished

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] Samsung Galaxt Tab A
 - OS: [e.g. iOS8.1] Android
 - Version [e.g. 22] 1.6.0

**Additional context**
This is from app not browser

**Comment by fm-sys** [comment] 2021-05-23 15:34
Are you sending the files "from" or "to" the app?

How old is your tablet? Unfortunately, I cannot reproduce this issue on any of my devices...

**Comment by Thewisem** [comment] 2021-05-23 18:39
Hmmm try making a work profile

**Comment by Thewisem** [comment] 2021-05-23 18:39
Have a hundred documents on it

**Comment by Thewisem** [comment] 2021-05-23 18:40
By work profile, apps like shelter use it

**Comment by Thewisem** [comment] 2021-05-23 18:41
And send on the work profile chrome 100 documents and recieve on the normal profile bromite(basically chrome so use chrome here). And here is the error

**Comment by fm-sys** [comment] 2021-12-15 07:12
@Thewisem  Can you tell me whether this issue is still relevant?

**Comment by fm-sys** [comment] 2021-12-31 09:44
Hi @Thewisem,

I will close the issue for now, due to the lack of necessary information. Feel free to comment if you have more details... I will reopen the issue as soon as I can reproduce it.

**Closed by fm-sys** 2021-12-31 09:44 UTC
Labels: bug, Waiting for more information
